# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-20 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nonce')),
                ('amount_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('reference', models.CharField(default=None, max_length=255, null=True)),
                ('comment', models.CharField(default=None, max_length=255, null=True)),
                ('payment_system_id', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('currency', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('uni', models.CharField(blank=True, max_length=60, null=True, verbose_name='Uni')),
                ('nonce', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nonce')),
                ('token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Token')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('handler', models.CharField(max_length=100, null=True)),
                ('bin', models.IntegerField(default=None, null=True)),
                ('fee_deposit', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('fee_withdraw', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('is_slow', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('identifier', models.CharField(max_length=100)),
                ('secondary_identifier', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('beneficiary', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bic', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('physical_address_bank', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('physical_address_owner', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('currency', models.ManyToManyField(to='core.Currency')),
                ('payment_method', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentMethod')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=36, verbose_name='Card_id')),
                ('address_id', models.CharField(max_length=42, verbose_name='Address_id')),
                ('currency', models.CharField(choices=[('BTC', 'BTC'), ('LTC', 'LTC'), ('ETH', 'ETH')], max_length=3, verbose_name='Currency')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cards',
                'verbose_name': 'Card',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='paymentcredentials',
            name='payment_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentPreference'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_preference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentPreference'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='paymentpreference',
            unique_together=set([('user', 'identifier', 'payment_method')]),
        ),
    ]
