# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='pays_deposit_fee',
            field=models.IntegerField(choices=[(0, 'CUSTOMER'), (1, 'MERCHANT')], default=0),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='pays_withdraw_fee',
            field=models.IntegerField(choices=[(0, 'CUSTOMER'), (1, 'MERCHANT')], default=1),
        ),
    ]
