# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20170301_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentpreference',
            old_name='enabled',
            new_name='buy_enabled',
        ),
        migrations.AddField(
            model_name='paymentpreference',
            name='sell_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
