# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20170227_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='allowed_amount_unpaid',
            field=models.DecimalField(decimal_places=2, default=0.01, help_text='Allowed difference between order amount (ticker_amount) and payment amount (amount_cash).', max_digits=14),
        ),
    ]
