# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-04 19:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_auto_20161215_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCards',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('card_id',
                 models.CharField(
                     max_length=36,
                     verbose_name='Card_id')),
                ('currency',
                 models.CharField(
                     choices=[
                         ('BTC',
                          'BTC'),
                         ('LTC',
                          'LTC'),
                         ('ETH',
                          'ETH')],
                     max_length=3,
                     verbose_name='Currency')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('user',
                 models.ForeignKey(
                     blank=True,
                     default=None,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'ordering': ['-created'],
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
