# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20161215_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentpreference',
            old_name='main_type',
            new_name='beneficiary',
        ),
        migrations.RenameField(
            model_name='paymentpreference',
            old_name='sub_type',
            new_name='bic',
        ),
        migrations.AddField(
            model_name='paymentpreference',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
