# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_usercards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercards',
            name='address_id',
            field=models.CharField(max_length=42, verbose_name='Address_id'),
        ),
    ]
