# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_location'),
        ('payments', '0003_auto_20170302_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpreference',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
    ]
