# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20170302_1240'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paymentcredentials',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paymentpreference',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
