# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20170331_1431'),
        ('payments', '0004_paymentpreference_location'),
    ]

    operations = [
    ]
