# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20170108_1556'),
        ('payments', '0003_auto_20170117_1049'),
    ]

    operations = [
    ]
