# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_merge_20170331_1519'),
        ('payments', '0003_paymentmethod_allowed_amount_unpaid'),
    ]

    operations = [
    ]
