# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_merge_20170117_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpreference',
            name='physical_address_bank',
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True),
        ),
        migrations.AddField(
            model_name='paymentpreference',
            name='physical_address_owner',
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True),
        ),
    ]
