# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20170118_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_system_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentpreference',
            name='secondary_identifier',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
