# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170331_1431'),
        ('payments', '0006_merge_20170406_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('validation_error', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paymentpreference',
            name='ccexp',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='paymentpreference',
            name='cvv',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
