# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20170411_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='checkout_type',
            field=models.IntegerField(
                choices=[
                    (0,
                     'MANUAL'),
                    (1,
                     'AUTO'),
                    (2,
                     'MANUAL & AUTO'),
                    (3,
                     'Checkout on Order Success')],
                default=0),
        ),
    ]
