# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20170123_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpreference',
            name='secondary_identifier',
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True),
        ),
    ]
