# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentmethod_checkout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='required_verification_buy',
            field=models.BooleanField(default=False),
        ),
    ]
