# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20170124_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpreference',
            name='user',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
