# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentmethod_checkout_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercards',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCards',
        ),
    ]
