# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymentmethod_required_verification_buy'),
        ('payments', '0009_auto_20170420_2159'),
    ]

    operations = [
    ]
