# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20170124_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_system_id',
            field=models.CharField(
                default=None,
                max_length=255,
                null=True,
                unique=True),
        ),
    ]
