# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_merge_20170505_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentpreference',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
