# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_country'),
        ('payments', '0011_auto_20170619_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='allowed_countries',
            field=models.ManyToManyField(help_text='Specifies the countires for which this payment method is allowed. If there is no countries specified then it is allowed for all of them', to='core.Country'),
        ),
    ]
