# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_paymentmethod_allowed_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='secondary_payment_system_id',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
