# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_moderator_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='moderator_flag',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
