# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_secondary_payment_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('W', 'WITHDRAW'), ('D', 'DEPOSIT')], max_length=1, null=True),
        ),
    ]
