# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0013_auto_20170129_2352'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentpreference',
            unique_together=set([('user', 'identifier', 'payment_method')]),
        ),
    ]
