# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpreference',
            name='provider_system_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
