# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_paymentpreference_provider_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='auth_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
