# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20170209_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='moderator_flag',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='fee',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fee_deposit',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                max_digits=5,
                null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fee_withdraw',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                max_digits=5,
                null=True),
        ),
    ]
