# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20170210_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='moderator_flag',
        ),
    ]
