# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 18:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_payment_auth_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(default=None, max_length=39, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('payload_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('valid_checksum', models.BooleanField(default=False)),
                ('valid_timestamp', models.BooleanField(default=False)),
                ('valid_ip', models.BooleanField(default=False)),
                ('payment_created', models.BooleanField(default=False, help_text='It is possible to get more than one PushRequest for one payment. If this is True - payment was created with this PushRequest.')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='failedrequest',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='failedrequest',
            name='ip',
            field=models.CharField(default=None, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='failedrequest',
            name='payload_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
