# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_payment_auth_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('W', 'WITHDRAW'), ('D', 'DEPOSIT'), ('R', 'REFUND')], max_length=1, null=True),
        ),
    ]
