# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0011_auto_20180313_0912'),
        ('payments', '0017_auto_20180309_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpreference',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='verification.VerificationTier'),
        ),
    ]
