# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_auto_20180309_1855'),
        ('payments', '0017_auto_20180228_1149'),
    ]

    operations = [
    ]
