# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_merge_20180312_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpreference',
            name='is_immediate_payment',
            field=models.BooleanField(default=False, help_text='This should be moved to PaymentMethod when methods will be created automatically on Safe Charge PushRequests.'),
        ),
    ]
