# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_merge_20180312_1406'),
        ('payments', '0018_paymentpreference_tier'),
    ]

    operations = [
    ]
