# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20180316_1223'),
        ('payments', '0019_paymentpreference_is_immediate_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='minimal_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='minimal_fee_currency',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
        ),
    ]
