# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_merge_20180319_1411'),
        ('payments', '0020_auto_20180327_1322'),
    ]

    operations = [
    ]
