# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-31 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_merge_20180329_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpreference',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
