# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20180331_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpreference',
            name='push_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PushRequest'),
        ),
    ]
