# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20180320_1302'),
        ('payments', '0022_auto_20180331_1336'),
    ]

    operations = [
    ]
