# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-31 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_auto_20180529_1407'),
        ('payments', '0023_paymentpreference_push_request'),
    ]

    operations = [
    ]
