# Generated by Django 2.0.7 on 2018-09-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_auto_20180906_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='phone',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
