# Generated by Django 2.0.7 on 2018-10-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20181026_1546'),
        ('payments', '0027_auto_20180910_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='limit_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.LimitOrder'),
        ),
    ]
