# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import verification.models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_auto_20170331_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='identity_document',
            field=models.FileField(
                upload_to=verification.models.Verification.identity_file_name),
        ),
        migrations.AlterField(
            model_name='verification',
            name='utility_document',
            field=models.FileField(
                upload_to=verification.models.Verification._utility_file_name),
        ),
    ]
