# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_payment_type'),
        ('verification', '0005_auto_20170627_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='payment_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentPreference'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
