# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_auto_20171128_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='id_status',
            field=models.CharField(blank=True, choices=[('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('OK', 'Approved')], default='PENDING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='util_status',
            field=models.CharField(blank=True, choices=[('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('OK', 'Approved')], default='PENDING', max_length=10, null=True),
        ),
    ]
