# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0008_verification_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='note',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
