# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import verification.models
import verification.validators


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0009_verification_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to=verification.models.Verification.identity_file_name, validators=[verification.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='utility_document',
            field=models.FileField(blank=True, null=True, upload_to=verification.models.Verification._utility_file_name, validators=[verification.validators.validate_image_extension]),
        ),
    ]
