# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0011_auto_20180313_0912'),
        ('verification', '0012_verification_user_input_comment'),
    ]

    operations = [
    ]
