# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import verification.models
import verification.validators


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0013_merge_20180329_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('document_status', models.CharField(blank=True, choices=[('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('OK', 'Approved')], default='PENDING', max_length=10, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=verification.models.VerificationDocument.document_file_name, validators=[verification.validators.validate_image_extension])),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.DocumentType')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.Verification')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='verificationtier',
            name='level',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationtier',
            name='upgrade_note',
            field=models.CharField(default='Contact Support', max_length=255),
        ),
        migrations.AddField(
            model_name='verificationtier',
            name='required_documents',
            field=models.ManyToManyField(to='verification.DocumentType'),
        ),
    ]
