# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-17 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0014_auto_20180416_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='api_key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
