# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20180316_1223'),
        ('verification', '0015_documenttype_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='whitelisted_address_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='whitelisted_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
        migrations.AddField(
            model_name='verificationtier',
            name='whitelisting_required',
            field=models.BooleanField(default=False),
        ),
    ]
