# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0017_auto_20180502_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='full_name',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
