# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-30 12:35
from __future__ import unicode_literals

import audit_log.models.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0018_auto_20180530_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_verification_verification_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='verification',
            name='created_with_session_key',
            field=audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_verification_verification_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='verification',
            name='modified_with_session_key',
            field=audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_verification_verificationdocument_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='created_with_session_key',
            field=audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_verification_verificationdocument_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='modified_with_session_key',
            field=audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True),
        ),
    ]
