# Generated by Django 2.0.7 on 2018-08-22 15:37

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0019_auto_20180530_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelimit',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='verification.VerificationTier'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_verification_verification_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_verification_verification_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='payment_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.PaymentPreference'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_verification_verificationdocument_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='verification.DocumentType'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_verification_verificationdocument_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='verification.Verification'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='whitelisted_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Address'),
        ),
    ]
