# Generated by Django 2.0.7 on 2018-09-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0020_auto_20180822_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='admin_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='admin_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
