# Generated by Django 2.0.7 on 2018-09-25 10:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20180822_1537'),
        ('core', '0066_remove_transactionprice_type'),
        ('verification', '0022_auto_20180907_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=255)),
                ('used', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycPushRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(default=None, max_length=39, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('payload_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('identification_status', models.CharField(blank=True, max_length=127, null=True)),
                ('identification_approved', models.BooleanField(default=False)),
                ('valid_link', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=127, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('doc_expiration', models.DateField(blank=True, null=True)),
                ('issuing_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issuing_countries', to='core.Country')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nationalities', to='core.Country')),
                ('selected_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selected_countries', to='core.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='kyc_push',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='verification.KycPushRequest'),
        ),
    ]
