# Generated by Django 2.0.7 on 2018-10-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0023_auto_20180925_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitytoken',
            name='first_name',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='identitytoken',
            name='last_name',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='identitytoken',
            name='scan_ref',
            field=models.CharField(blank=True, max_length=37, null=True),
        ),
        migrations.AddField(
            model_name='kycpushrequest',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='verification.IdentityToken'),
        ),
        migrations.AlterField(
            model_name='identitytoken',
            name='token',
            field=models.CharField(max_length=2049),
        ),
    ]
