# Generated by Django 2.0.7 on 2019-01-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0026_verificationdocument_contains_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='rule_type',
            field=models.IntegerField(choices=[(0, 'EQUAL'), (1, 'IN'), (2, 'LESS'), (3, 'MORE')]),
        ),
    ]
