# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-20 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('about_us', 'about_us'), ('careers', 'careers'), ('press', 'press'), ('conference', 'conference'), ('legal_privacy', 'legal_privacy'), ('security', 'security'), ('faq', 'faq'), ('fees', 'fees'), ('support', 'support')], default=None, max_length=50)),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Espanol')], default=('ru', 'Russian'), max_length=2, null=True)),
                ('head', models.TextField(default=None, null=True)),
                ('written_by', models.TextField(default=None, null=True)),
                ('body', models.TextField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OgResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('about_us', 'about_us'), ('careers', 'careers'), ('press', 'press'), ('conference', 'conference'), ('legal_privacy', 'legal_privacy'), ('security', 'security'), ('faq', 'faq'), ('fees', 'fees'), ('support', 'support')], default=None, max_length=50)),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Espanol')], default=('ru', 'Russian'), max_length=2, null=True)),
                ('resource_url', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, default=None, max_length=255)),
                ('title', models.CharField(blank=True, default=None, max_length=255)),
                ('site_name', models.CharField(blank=True, default=None, max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=500)),
                ('use_og', models.BooleanField(default=True)),
                ('page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources_sets', to='articles.CmsPage')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
