# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170228_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspage',
            name='name',
            field=models.CharField(choices=[('faq', 'faq'), ('fees', 'fees'), ('support', 'support'), ('affiliates', 'affiliates'), ('about_us', 'about_us'), ('careers', 'careers'), ('press', 'press'), ('conference', 'conference'), ('legal_privacy', 'legal_privacy'), ('security', 'security')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='ogresource',
            name='name',
            field=models.CharField(choices=[('faq', 'faq'), ('fees', 'fees'), ('support', 'support'), ('affiliates', 'affiliates'), ('about_us', 'about_us'), ('careers', 'careers'), ('press', 'press'), ('conference', 'conference'), ('legal_privacy', 'legal_privacy'), ('security', 'security')], default=None, max_length=50),
        ),
    ]
