# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170228_1035'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cmspage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ogresource',
            managers=[
            ],
        ),
    ]
