# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170305_0151'),
        ('articles', '0004_auto_20170301_1309'),
    ]

    operations = [
    ]
