# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_merge_20170330_1332'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cmspage',
            managers=[
                ('active_objects',
                 django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ogresource',
            managers=[
                ('active_objects',
                 django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='name',
            field=models.CharField(
                choices=[
                    ('about_us',
                     'about_us'),
                    ('careers',
                     'careers'),
                    ('press',
                     'press'),
                    ('conference',
                     'conference'),
                    ('legal_privacy',
                     'legal_privacy'),
                    ('security',
                     'security'),
                    ('faq',
                     'faq'),
                    ('fees',
                     'fees'),
                    ('support',
                     'support'),
                    ('affiliates',
                     'affiliates')],
                default=None,
                max_length=50),
        ),
        migrations.AlterField(
            model_name='ogresource',
            name='name',
            field=models.CharField(
                choices=[
                    ('about_us',
                     'about_us'),
                    ('careers',
                     'careers'),
                    ('press',
                     'press'),
                    ('conference',
                     'conference'),
                    ('legal_privacy',
                     'legal_privacy'),
                    ('security',
                     'security'),
                    ('faq',
                     'faq'),
                    ('fees',
                     'fees'),
                    ('support',
                     'support'),
                    ('affiliates',
                     'affiliates')],
                default=None,
                max_length=50),
        ),
    ]
