# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-25 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170331_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspage',
            name='locale',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Spanish'), ('ca', 'Catalan'), ('zh-hans', 'Simplified Chinese')], default=('ru', 'Russian'), max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ogresource',
            name='locale',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Spanish'), ('ca', 'Catalan'), ('zh-hans', 'Simplified Chinese')], default=('ru', 'Russian'), max_length=2, null=True),
        ),
    ]
