# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20161219_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogresource',
            name='body',
        ),
        migrations.AddField(
            model_name='ogresource',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='ogresource',
            name='use_og',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ogresource',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='ogresource',
            name='site_name',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='ogresource',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
