# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20161219_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogresource',
            name='page',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='resources_sets',
                to='articles.CmsPage'),
        ),
    ]
