FORMAT: 1A
HOST: https://nexchange.co.uk/
# nexchange

API for crypto currency exchange.

## Get Currencies [/en/api/v1/currency/]


### Get Currencies [GET]
 Get all supported currencies.

+ Response 200 (application/json)
    + Attributes (array[Currency])
    + Body

            [
              {
                "code": "BTC",
                "name": "bitcoin",
                "min_confirmations": 1,
                "is_crypto": true,
                "minimal_amount": "0.01000000",
                "is_base_of_enabled_pair": true,
                "is_quote_of_enabled_pair": true,
                "has_enabled_pairs": true
              },
              {
                "code": "LTC",
                "name": "litecoin",
                "min_confirmations": 6,
                "is_crypto": true,
                "minimal_amount": "0.50000000",
                "is_base_of_enabled_pair": true,
                "is_quote_of_enabled_pair": true,
                "has_enabled_pairs": true
              }
            ]

## Get Pairs [/en/api/v1/pair/]


### Get Pairs [GET]
 Get all supported currency pairs.

+ Response 200 (application/json)
    + Attributes (array[PairSimple])
    + Body

            [
              {
                "name": "BTCLTC",
                "base": "BTC",
                "quote": "LTC",
                "fee_ask": "0.00100000",
                "fee_bid": "0.00100000"
              },
              {
                "name": "BTCETH",
                "base": "BTC",
                "quote": "ETH",
                "fee_ask": "0.00100000",
                "fee_bid": "0.00100000"
              }
            ]

## Latest Ticker [/en/api/v1/price/{pair_name}/latest/]

+ Parameters
    + pair_name (required, string, `BTCLTC`) - Name of exchanged pair i.e. BTCLTC, LTCBTC, ETHBTC...


### Get Latest Ticker [GET]
 Gets BTC/LTC latest price

+ Response 200 (application/json)
    + Attributes (array[Price])
    + Body

            [
              {
                "created_on":"2017-08-15T12:45:01.443265Z",
                "unix_time":"1502801101",
                "ticker":{
                  "ask":"97.06196063",
                  "bid":"96.33558341"
                }
              }
            ]


## Ticker History [/en/api/v1/price/{pair_name}/history/{?hours,data_points}]

+ Parameters
    + pair_name (required, string, `BTCLTC`) - Name of exchanged pair i.e. BTCLTC, LTCBTC, ETHBTC...
    + hours (double, `0.1`) - How many hours back would you like to get prices for. Amount of hours to check i.e. 0.3 means 18 min, 2 - 2 hours.
    + data_points (int, `3`) - How many data points in the selected hour range would you like to get. For example, If you pass 1 hour and data_points=60, you will get 1 data point per minute (our max supported resolution), if you pass hour=1 and data_points=30 you will get one point per 2 minutes.

### Get Ticker History [GET]
 Returns price history for selected pair.

+ Response 200 (application/json)
    + Attributes (array[Price])
    + Body

            [
              {
                "created_on": "2017-08-15T13:37:05.746301Z",
                "unix_time": "1502804225",
                "ticker": {
                  "ask": "93.50770668",
                  "bid": "93.01675978"
                }
              },
              {
                "created_on": "2017-08-15T13:38:05.877523Z",
                "unix_time": "1502804285",
                "ticker": {
                  "ask": "92.71952575",
                  "bid": "91.87051683"
                }
              }
            ]


## Get Orders [/en/api/v1/orders/{?page,page_size}]

+ Parameter
    + page (int, `1`) - page number.
    + page_size (int, `3`) - number of orders in one page.


### Get Orders [GET]
   Returns orders.

+ Response 200 (application/json)
    + Attributes (Orders)
    + Body

            {
              "count": 21,
              "next": "http://localhost:8000/en/api/v1/orders/?page=2&page_size=3",
              "previous": null,
              "results": [
                {
                  "amount_base": "0.50000000",
                  "is_default_rule": false,
                  "unique_reference": "LOUA3",
                  "amount_quote": "7.17000000",
                  "pair": 2,
                  "withdraw_address": {
                    "type": "W",
                    "name": "",
                    "address": "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
                    "currency_code": "BTC"
                  },
                  "created_on": "2017-08-16T07:27:04.964665Z",
                  "from_default_rule": false,
                  "order_type": 1,
                  "deposit_address": {
                    "type": "D",
                    "name": "",
                    "address": "0xF00667496B353d77492e0f7167843d5d5802030b",
                    "currency_code": "ETH"
                  },
                  "pair_name": "BTCETH"
                },
                {
                  "amount_base": "0.50000000",
                  "is_default_rule": false,
                  "unique_reference": "OMTE7",
                  "amount_quote": "7.17000000",
                  "pair": 2,
                  "withdraw_address": null,
                  "created_on": "2017-08-16T07:27:01.099226Z",
                  "from_default_rule": false,
                  "order_type": 1,
                  "deposit_address": {
                    "type": "D",
                    "name": "",
                    "address": "0x7b92910B52DAE980702d4EDc270B031b60359904",
                    "currency_code": "ETH"
                  },
                  "pair_name": "BTCETH"
                },
                {
                  "amount_base": "0.50000000",
                  "is_default_rule": false,
                  "unique_reference": "57KJB",
                  "amount_quote": "7.17000000",
                  "pair": 2,
                  "withdraw_address": null,
                  "created_on": "2017-08-16T07:26:57.076292Z",
                  "from_default_rule": false,
                  "order_type": 1,
                  "deposit_address": {
                    "type": "D",
                    "name": "",
                    "address": "0x408a05c9F62E8eaECd258BB27213ee6e59d2E7Ef",
                    "currency_code": "ETH"
                  },
                  "pair_name": "BTCETH"
                }
              ]
            }

## Get Order [/en/api/v1/orders/{unique_reference}/]

+ Parameter
    + unique_reference (`JN0UR`) - unique reference of the order.


### Get Order [GET]
   Get order data.

+ Request

    + Headers

            Authorization: Basic ZGVtbzpEZW1vNFRoZWJlc3Q=


+ Response 200 (application/json)
    + Attributes (BaseOrder)

    + Body

            {
              "amount_base":"0.50000000",
              "is_default_rule":false,
              "unique_reference":"1CPL5",
              "amount_quote":"48.00000000",
              "pair":1,"withdraw_address":null,
              "created_on":"2017-08-16T10:36:02.248639Z",
              "from_default_rule":false,"order_type":1,
              "deposit_address":{
                "type":"D",
                "name":"",
                "address":"LewxThDasEA2JTDVDdGMot92kG6XYNFNQN",
                "currency_code":"LTC"
              },
              "pair_name":"BTCLTC"
            }


## Get User Orders [/en/api/v1/users/me/orders/{?page,page_size}]

+ Parameter
    + page (int, `1`) - page number.
    + page_size (int, `3`) - number of orders in one page.


### Get User Orders [GET]
   Get user orders.

+ Request

    + Headers

            Authorization: Basic ZGVtbzpEZW1vNFRoZWJlc3Q=


+ Response 200 (application/json)
    + Attributes (Orders)

    + Body

            {
              "count": 1,
              "next": {},
              "previous": {},
              "results": [
                {
                  "amount_base": "0.50000000",
                  "is_default_rule": false,
                  "unique_reference": "1CPL5",
                  "amount_quote": "48.00000000",
                  "pair": 1,
                  "withdraw_address": {},
                  "created_on": "2017-08-16T10:36:02.248639Z",
                  "from_default_rule": false,
                  "order_type": 1,
                  "deposit_address": {
                    "type": "D",
                    "name": "",
                    "address": "LewxThDasEA2JTDVDdGMot92kG6XYNFNQN",
                    "currency_code": "LTC"
                  },
                  "status": 1,
                  "payment_window": 60,
                  "payment_deadline": "2017-08-16T11:36:02.248639Z"
                  "status_name":[
                    [
                      1,
                      "INITIAL"
                    ]
                  ],
                  "transactions":[{
                    "created_on":"2017-08-16T22:14:46.680082Z",
                    "modified_on":"2017-08-16T22:14:46.680105Z",
                    "type":"W",
                    "address_to":1,
                    "tx_id":"asdfsadfsadf",
                    "confirmations":0,
                    "amount":"0.01000000",
                    "is_verified":false,
                    "is_completed":false,
                    "time":null,
                    "currency":null
                  }]
                }
              ]
            }


## Get User Order [/en/api/v1/users/me/orders/{unique_reference}/]

+ Parameter
    + unique_reference (`JN0UR`) - unique reference of the order.


### Get User Order [GET]
   Get user order.

+ Request

    + Headers

            Authorization: Basic ZGVtbzpEZW1vNFRoZWJlc3Q=


+ Response 200 (application/json)
    + Attributes (PrivateOrder)

    + Body

            {
              "amount_base": "0.50000000",
              "is_default_rule": false,
              "unique_reference": "1CPL5",
              "amount_quote": "48.00000000",
              "pair": 1,
              "withdraw_address": {},
              "created_on": "2017-08-16T10:36:02.248639Z",
              "from_default_rule": false,
              "order_type": 1,
              "deposit_address": {
                "type": "D",
                "name": "",
                "address": "LewxThDasEA2JTDVDdGMot92kG6XYNFNQN",
                "currency_code": "LTC"
              },
              "status": 1,
              "payment_window": 60,
              "payment_deadline": "2017-08-16T11:36:02.248639Z"
              "status_name":[
                [
                  1,
                  "INITIAL"
                ]
              ],
              "transactions":[{
                "created_on":"2017-08-16T22:14:46.680082Z",
                "modified_on":"2017-08-16T22:14:46.680105Z",
                "type":"W",
                "address_to":1,
                "tx_id":"asdfsadfsadf",
                "confirmations":0,
                "amount":"0.01000000",
                "is_verified":false,
                "is_completed":false,
                "time":null,
                "currency":null
              }]
            }

## Create User Order [/en/api/v1/users/me/orders/]


### Create User Order [POST]
   Create order.

+ Request (application/json)

    + Body

            {
                "amount_base": 3,
                "is_default_rule": false,
                "pair": {
                  "name": "LTCBTC"
                },
                "withdraw_address": {
                    "address": "LYUoUn9ATCxvkbtHseBJyVZMkLonx7agXA"
                }
            }
    + Headers

            Authorization: Basic ZGVtbzpEZW1vNFRoZWJlc3Q=

+ Response 201 (application/json)
    + Attributes (MinimalOrder)

    + Body

            {
              "amount_base": "3.00000000",
              "is_default_rule": false,
              "unique_reference": "L18XD",
              "amount_quote": "0.03110000",
              "pair": {
                  "name": "LTCBTC"
                },
              "withdraw_address": {
                "type": "W",
                "name": "",
                "address": "LYUoUn9ATCxvkbtHseBJyVZMkLonx7agXA",
                "currency_code": "LTC"
              },
              "status_name":[
                [
                  1,
                  "INITIAL"
                ]
              ],
              "transactions":[{
                "created_on":"2017-08-16T22:14:46.680082Z",
                "modified_on":"2017-08-16T22:14:46.680105Z",
                "type":"W",
                "address_to":1,
                "tx_id":"asdfsadfsadf",
                "confirmations":0,
                "amount":"0.01000000",
                "is_verified":false,
                "is_completed":false,
                "time":null,
                "currency":null
              }]
            }

## Create Anonymous Order [/en/api/v1/orders/]


### Create Anonymous Order [POST]
   Create order.

+ Request (application/json)

    + Body

            {
                "amount_base": 3,
                "is_default_rule": false,
                "pair": {
                  "name": "LTCBTC"
                },
                "withdraw_address": {
                    "address": "LYUoUn9ATCxvkbtHseBJyVZMkLonx7agXA"
                }
            }

+ Response 201 (application/json)
    + Attributes (MinimalOrder)

    + Body

            {
              "amount_base": "3.00000000",
              "is_default_rule": false,
              "unique_reference": "L18XD",
              "amount_quote": "0.03110000",
              "pair": 123,
              "withdraw_address": {
                "type": "W",
                "name": "",
                "address": "LYUoUn9ATCxvkbtHseBJyVZMkLonx7agXA",
                "currency_code": "LTC"
              }
            }


# Data Structures

## Currency
+ `code` (required) - currency code.
+ `name` - currency name.
+ `min_confirmations` (number) - minimum number of confirmations required to approve a transaction on this currency's blockchain. Only relevant for currencies that have 'is_crypto' = true
+ `is_crypto` (boolean) - if true, this is a crypto currency, else it is a fiat currency.
+ `minimal_amount` -  minimal amount allowed on this currency transaction.
+ `is_base_of_enabled_pair` (boolean) - true if where is pair with this currency as base.
+ `is_quote_of_enabled_pair` (boolean) - true if exists a pair with this currency as quote.
+ `has_enabled_pairs` (boolean) -  true if pair with this currency as base or quote and enabled exchange exists.

## PairSimple
+ `name` (required) - name of the pair. i.e. BTCLTC for base BTC(bitcoin) and quote LTC(litecoin) pair.
+ `base` (required) - base currency code.
+ `quote` (required) - quote currency code.
+ `fee_ask` (required) - asking fee, 0.001 equals 0.1%.
+ `fee_bid` (required) - biding fee, 0.001 equals 0.1% (depreciated).

## Pair
+ `name` (required) - name of the pair. i.e. BTCLTC for base BTC(bitcoin) and quote LTC(litecoin) pair.
+ `base` (Currency, required) - base currency.
+ `quote` (Currency, required) - quote currency.
+ `fee_ask` (number, required) - asking fee, 0.001 equals 0.1%.
+ `fee_bid` (number, required) - biding fee, 0.001 equals 0.1% (depreciated).

## Ticker
+ `ask` (required) - ask price.
+ `bid` (required) - bid price.

## Price
+ `created_on` (required) -  price creation UTC time.
+ `unix_time` (required) - price creation unix timestamp.
+ `ticker` (Ticker, required) - ticker.

## Address
+ `type` (required) - "W" for withdraw and "D" for Deposit.
+ `name` (optional, nullable) - name of the address.
+ `address` (required) - crypto currency address i.e. 0x408a05c9F62E8eaECd258BB27213ee6e59d2E7Ef
+ `currency_code` (required) - currency code i.e. ETH.

## Transaction
+ `created_on` (required) - UTC time of creation.
+ `modified_on` (required) - UTC time of last modification.
+ `type` (required) - "W" for withdraw and "D" for Deposit.
+ `address_to` (number, required) - recepient address ID.
+ `tx_id` (nullable) - transaction ID.
+ `confirmations` (number, required) - transaction confirmations.
+ `amount` (required) - transaction amount.
+ `is_verified` (boolean, required) - verification status.
+ `is_completed` (boolean, required) - completion status.
+ `time` (nullable) - UTC time of transaction.
+ `currency` (nullable) - currency code.


## MinimalOrder
+ `amount_base` (required) - amount of base currency which user gets.
+ `is_default_rule` (boolean, required) - convert any incoming funds to this address automatically (the withdraw_address defined on the same order).
+ `unique_reference` (required) - unique ID of an order.
+ `amount_quote` (required) - amount of base currency which user sends.
+ `withdraw_address` (Address, nullable) - address where user gets his funds.
+ `transactions` (array[Transaction]) - order transactions.

## BaseOrder (MinimalOrder)
+ `created_on` (fixed) - time of order creation (timestamp)
+ `modified_on` (fixed) - Latest time on which this order was updated
+ `deposit_address` (Address, required) - address where user sends his funds.
+ `from_default_rule` (boolean, required) - indicates that the order was created as a result of `is_default_rule` as described above.
+ 'pair' (Pair) - exchange pair.

## PrivateOrder (BaseOrder)
+ `status` (number, required) - order status 2 - Initial, 2 - Paid...

## Orders
+ `count` (number, required) - number of orders.
+ `next` (string, nullable) - link to the next page.
+ `previous` (string, nullable) - link to previous page.
+ `results` (array[BaseOrder])
