version: '2'
services:
    redis:
      image: redis:2.8.19
      hostname: redis
      logging:
          driver: syslog
          options:
            syslog-address: ${LOGSTASH_ADDRESS}:${LOGSTASH_PORT}
    postgis:
        image: mdillon/postgis
        environment:
           POSTGRES_USER: ${POSTGIS_ENV_POSTGRES_USER}
           POSTGRES_PASSWORD: ${POSTGIS_ENV_POSTGRES_PASSWORD}
           POSTGRES_DB: ${POSTGIS_ENV_POSTGRES_DB}
        volumes:
            - /mnt/${DB_VOL}/nexchange/database:/var/lib/postgresql/data
        restart: always
#        logging:
#            driver: syslog
#            options:
#              syslog-address: tcp://${LOGSTASH_ADDRESS}:${LOGSTASH_PORT}
    app:
        image: onitsoft/nexchange:${DOCKER_IMAGE_TAG}
        volumes:
            - /nexchange/mediafiles:/usr/share/nginx/html/media
            - /nexchange/staticfiles:/usr/share/nginx/html/static
            - /nexchange/etc/nginx/.htpasswd:/etc/nginx/.htpasswd

        links:
            - postgis
            - redis
        ports:
          - "65223:65223"
        restart: always
#        logging:
#            driver: syslog
#            options:
#              syslog-address: ${LOGSTASH_ADDRESS}:${LOGSTASH_PORT}
    web:
        image: onitsoft/nginx
        volumes:
            - /nexchange/etc/letsencrypt:/etc/letsencrypt
            - /nexchange/etc/nginx/ssl:/etc/nginx/ssl
            - /nexchange/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /nexchange/etc/nginx/.htpasswd:/etc/nginx/.htpasswd
            - /nexchange/mediafiles:/usr/share/nginx/html/media
            - /nexchange/staticfiles:/usr/share/nginx/html/static
        ports:
            - "80:80"
            - "443:443"
        links:
            - app
        restart: always
#        logging:
#            driver: syslog
#            options:
#              syslog-address: ${LOGSTASH_ADDRESS}:${LOGSTASH_PORT}
