# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_market'),
        ('orders', '0022_order_user_provided_amount'),
        ('risk_management', '0004_account_is_main_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('cover_type', models.IntegerField(choices=[(0, 'SELL'), (1, 'BUY')], default=1)),
                ('amount_base', models.DecimalField(decimal_places=8, max_digits=18)),
                ('amount_quote', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('cover_id', models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, unique=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
                ('orders', models.ManyToManyField(related_name='covers', to='orders.Order')),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pair')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
