# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 12:42
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0005_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='minimal_reserve',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='account',
            name='required_reserve',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
    ]
