# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-20 13:35
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0006_auto_20171106_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, 'INITIAL'), (5, 'PRE-EXECUTED'), (9, 'EXECUTED')], default=1),
        ),
    ]
