# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-12 13:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import risk_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180119_1512'),
        ('risk_management', '0008_portfoliolog_reservelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateTimeField(blank=True, default=risk_management.models.PNL.get_defult_date_from, null=True)),
                ('date_to', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('average_ask', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('volume_ask', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('average_bid', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('volume_bid', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('pair_order_count', models.IntegerField(blank=True, null=True)),
                ('opposite_pair_order_count', models.IntegerField(blank=True, null=True)),
                ('exit_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('rate_btc', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('rate_usd', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('rate_eur', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('rate_eth', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PNLSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateTimeField(blank=True, default=risk_management.models.PNLSheet.get_defult_date_from, null=True)),
                ('date_to', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pnl',
            name='pnl_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management.PNLSheet'),
        ),
    ]
