# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-16 12:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0009_auto_20180212_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnl',
            name='base_volume_ask',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='pnl',
            name='base_volume_bid',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
    ]
