# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20180316_1223'),
        ('risk_management', '0010_auto_20180216_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('disable_quote', models.BooleanField(default=True)),
                ('disable_base', models.BooleanField(default=True)),
                ('user_visible_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
