# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-17 18:46
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0011_reserve_maximal_limit_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='margin_balance',
            new_name='allowed_diff',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='maximal_limit_balance',
            new_name='maximum_level',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='expected_balance',
            new_name='target_level',
        ),
        migrations.AddField(
            model_name='reserve',
            name='minimum_level',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
    ]
