# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-01 15:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0011_auto_20180228_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnl',
            name='pnl_btc',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
    ]
