# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0011_disabledcurrency'),
        ('risk_management', '0012_auto_20180417_1846'),
    ]

    operations = [
    ]
