# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 14:53
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_pair_disable_volume'),
        ('risk_management', '0014_reserve_minimum_main_account_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservesCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('amount_quote', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('amount_base', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('pair', models.ForeignKey(blank=True, help_text='Pair that is suggested to trade according to the reserve levels.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pair')),
                ('portfolio_log', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management.PortfolioLog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservesCoverSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('default', models.BooleanField(default=False)),
                ('coverable_part', models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='1 - 100%. Which part of required amount of reserve difference from target_level to cover.', max_digits=18)),
                ('currencies', models.ManyToManyField(related_name='currencies', to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='healthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservescover',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management.ReservesCoverSettings'),
        ),
        migrations.AddField(
            model_name='cover',
            name='reserve_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management.ReservesCover'),
        ),
    ]
