# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-11 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0012_pnl_pnl_btc'),
        ('risk_management', '0014_reserve_minimum_main_account_level'),
    ]

    operations = [
    ]
