# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-17 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0015_merge_20180511_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pnl',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='pnlsheet',
            options={'ordering': ['-created_on']},
        ),
    ]
