# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-21 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0016_auto_20180517_0656'),
        ('risk_management', '0015_auto_20180507_1453'),
    ]

    operations = [
    ]
