# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-28 15:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0017_merge_20180521_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnl',
            name='days',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='pnlsheet',
            name='days',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='reservescover',
            name='pnl_sheets',
            field=models.ManyToManyField(to='risk_management.PNLSheet'),
        ),
    ]
