# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-29 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0018_auto_20180528_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover',
            old_name='reserve_cover',
            new_name='reserves_cover',
        ),
    ]
