# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-08 10:03
from __future__ import unicode_literals

import audit_log.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk_management', '0019_auto_20180529_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicReservesCoverSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('minimum_rate_change', models.DecimalField(decimal_places=8, default=Decimal('0.05'), max_digits=18)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_risk_management_periodicreservescoversettings_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_risk_management_periodicreservescoversettings_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management.ReservesCoverSettings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reservescover',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservescover',
            name='discard',
            field=models.BooleanField(default=False),
        ),
    ]
