# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-08 12:25
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0021_periodicreservescoversettings_current_reserves_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-1, 'CANCELED'), (1, 'INITIAL'), (5, 'PRE-EXECUTED'), (9, 'EXECUTED')], default=1),
        ),
    ]
