# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-21 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0022_auto_20180608_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnl',
            name='volume_position_ratio',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
    ]
