# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-20 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0023_pnl_volume_position_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabledcurrency',
            name='disable_ticker_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disabledcurrency',
            name='disable_ticker_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disabledcurrency',
            name='disable_volume_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disabledcurrency',
            name='disable_volume_quote',
            field=models.BooleanField(default=False),
        ),
    ]
