# Generated by Django 2.0.7 on 2018-08-22 15:37

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0024_auto_20180820_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='risk_management.Reserve'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pair'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='reserves_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='risk_management.ReservesCover'),
        ),
        migrations.AlterField(
            model_name='periodicreservescoversettings',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risk_management_periodicreservescoversettings_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='periodicreservescoversettings',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_risk_management_periodicreservescoversettings_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AlterField(
            model_name='periodicreservescoversettings',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='risk_management.ReservesCoverSettings'),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pair'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='reservescover',
            name='pair',
            field=models.ForeignKey(blank=True, help_text='Pair that is suggested to trade according to the reserve levels.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pair'),
        ),
        migrations.AlterField(
            model_name='reservescover',
            name='portfolio_log',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='risk_management.PortfolioLog'),
        ),
        migrations.AlterField(
            model_name='reservescover',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='risk_management.ReservesCoverSettings'),
        ),
    ]
