# Generated by Django 2.0.7 on 2018-08-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0025_auto_20180822_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management.Account'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='covers', to='orders.Order'),
        ),
    ]
