# Generated by Django 2.0.7 on 2018-08-27 11:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0026_auto_20180823_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnl',
            name='pnl_btc',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='pnl_eth',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='pnl_eur',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='pnl_usd',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='rate_btc',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='rate_eth',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='rate_eur',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='rate_usd',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reservelog',
            name='rate_btc',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reservelog',
            name='rate_eth',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reservelog',
            name='rate_eur',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reservelog',
            name='rate_usd',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
    ]
