# Generated by Django 2.0.7 on 2019-01-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0028_auto_20180828_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='amount_base',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Currency'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('reserve', 'wallet')},
        ),
    ]
