# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-20 01:30
from __future__ import unicode_literals

import core.validators
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('W', 'WITHDRAW'), ('D', 'DEPOSIT')], max_length=1)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=42, validators=[core.validators.validate_bc])),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=10)),
                ('min_confirmations', models.IntegerField(blank=True, null=True)),
                ('min_confirmation_high', models.IntegerField(blank=True, null=True)),
                ('is_crypto', models.BooleanField(default=False)),
                ('fee_offset', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('flag_val', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('model_name', models.CharField(default=None, max_length=255)),
                ('flagged_id', models.PositiveIntegerField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('fee_ask', models.DecimalField(decimal_places=8, default=Decimal('0.01'), max_digits=18)),
                ('fee_bid', models.DecimalField(decimal_places=8, default=Decimal('0.01'), max_digits=18)),
                ('name', models.CharField(blank=True, max_length=8, null=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('W', 'WITHDRAW'), ('D', 'DEPOSIT')], max_length=1)),
                ('confirmations', models.IntegerField(default=0)),
                ('tx_id', models.CharField(default=None, max_length=65, null=True, unique=True)),
                ('tx_id_api', models.CharField(default=None, max_length=55, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('address_from', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_from', to='core.Address')),
                ('address_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_to', to='core.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
