# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170220_0130'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address',
            managers=[
            ],
        ),
    ]
