# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160519_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
