# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_window',
            field=models.IntegerField(default=60),
        ),
    ]
