# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_fakemigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_crypto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='min_confirmations_high',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
