# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170118_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='min_confirmations_high',
            new_name='min_confirmation_high',
        ),
    ]
