# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170331_1431'),
        ('core', '0005_location'),
    ]

    operations = [
    ]
