# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160520_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rate_usd_btc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rate_usd_rub',
        ),
    ]
