# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160520_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_reference',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
