# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 04:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20170331_1518'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
