# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 03:59
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160520_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number in internation format. eg. +555198786543', max_length=128),
        ),
    ]
