# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170131_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('flag_val', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('model_name', models.CharField(default=None, max_length=255)),
                ('flagged_id', models.PositiveIntegerField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
