# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170131_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='fee_offset',
            field=models.FloatField(default=0.0),
        ),
    ]
