# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 22:31
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20170417_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='card_id')),
                ('address', models.CharField(max_length=42, verbose_name='address_id')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TransactionApiMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('node', models.CharField(max_length=100)),
                ('start', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='currency',
            name='algo',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.01'), max_digits=18),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='ticker',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='wallet',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txs_from', to='core.Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txs_to', to='core.Address'),
        ),
        migrations.AddField(
            model_name='addressreserve',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
        ),
        migrations.AddField(
            model_name='addressreserve',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='reserve',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addr', to='core.AddressReserve'),
        ),
    ]
