# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_id',
            field=models.CharField(
                default=None,
                max_length=65,
                null=True,
                unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_id_api',
            field=models.CharField(
                default=None,
                max_length=55,
                null=True,
                unique=True),
        ),
    ]
