# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_currency_fee_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('fee_ask', models.DecimalField(decimal_places=8, default=Decimal('0.02'), max_digits=18)),
                ('fee_bid', models.DecimalField(decimal_places=8, default=Decimal('0.02'), max_digits=18)),
                ('name', models.CharField(blank=True, max_length=8, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='core.Currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_prices', to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
