# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160522_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='smstoken',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
