# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170210_1156'),
        ('core', '0010_pair'),
    ]

    operations = [
    ]
