# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_currency_median_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionapimapper',
            name='start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
