# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 17:27
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20170213_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='fee_ask',
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal('0.01'),
                max_digits=18),
        ),
        migrations.AlterField(
            model_name='pair',
            name='fee_bid',
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal('0.01'),
                max_digits=18),
        ),
    ]
