# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160521_1627'),
        ('core', '0012_auto_20160522_0407'),
    ]

    operations = [
    ]
