# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 01:40
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160524_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='withdraw_address',
            field=models.CharField(
                default='1EoZm6PFqh7FwzwU23t1oPSiCXDuHoZjgf',
                max_length=34,
                validators=[
                    core.validators.validate_bc]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text='Enter phone number in     internation format. eg. +555198786543',
                max_length=128),
        ),
    ]
