# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-28 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161126_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_id_api',
            field=models.CharField(default=None, max_length=55, null=True),
        ),
    ]
