# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge'),
        ('core', '0013_auto_20160523_1837'),
    ]

    operations = [
    ]
