# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-28 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transaction_tx_id_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_id',
            field=models.CharField(default=None, max_length=65, null=True),
        ),
    ]
