# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_id',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
