# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170518_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
    ]
