# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge'),
        ('core', '0015_auto_20160524_0238'),
    ]

    operations = [
    ]
