# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 00:01
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='withdraw_address',
            field=models.CharField(
                blank=True,
                max_length=35,
                null=True,
                validators=[
                    core.validators.validate_bc]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text='Enter phone number in internation format. eg. +555198786543',
                max_length=128),
        ),
    ]
