# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20161212_1530'),
        ('core', '0016_auto_20161210_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='user',
        ),
        migrations.DeleteModel(
            name='CmsPage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_preference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='referraltransaction',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='smstoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='address',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ReferralTransaction',
        ),
        migrations.DeleteModel(
            name='SmsToken',
        ),
    ]
