# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170623_1508'),
        ('core', '0017_currency_flagged'),
    ]

    operations = [
    ]
