# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_currency_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='important',
            new_name='major',
        ),
    ]
