# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20170630_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='flag_val',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
