# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160526_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.Payment'),
            preserve_default=False,
        ),
    ]
