# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170703_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='disable_ticker',
            field=models.BooleanField(default=False, help_text='Opt-out this Pair ticker gathering.'),
        ),
    ]
