# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 00:20
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20160526_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order', name='wallet', ), migrations.RemoveField(
            model_name='order', name='withdraw_address', ), migrations.AlterField(
                model_name='address', name='address', field=models.CharField(
                    max_length=35, validators=[
                        core.validators.validate_bc]), ), ]
