# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170707_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressreserve',
            name='need_balance_check',
            field=models.BooleanField(default=True),
        ),
    ]
