# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_paymentmethod_paymentpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsToken', fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_on', models.DateTimeField(
                        auto_now_add=True)), ('modified_on', models.DateTimeField(
                            auto_now=True)), ('deleted', models.BooleanField(
                                default=False)), ('disabled', models.BooleanField(
                                    default=False)), ('sms_token', models.CharField(
                                        blank=True, max_length=5)), ('user', models.ForeignKey(
                                            on_delete=django.db.models.deletion.CASCADE, related_name='sms_token', to=settings.AUTH_USER_MODEL)), ], options={
                'abstract': False, }, managers=[
                                                ('active_objects', django.db.models.manager.Manager()), ], ), migrations.RemoveField(
                                                    model_name='profile', name='sms_token', ), migrations.AlterField(
                                                        model_name='profile', name='phone', field=phonenumber_field.modelfields.PhoneNumberField(
                                                            help_text='Enter phone number in international format. eg. +555198786543', max_length=128), ), ]
