# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 21:08
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_addressreserve_need_balance_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='minimal_amount',
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal('0.01'),
                help_text='Minimal amount that can be set as order base.',
                max_digits=18),
        ),
    ]
