# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20160530_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstoken',
            name='sms_token',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
