# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20160531_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='Handler',
        ),
    ]
