# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170731_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
