# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_paymentmethod_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
