# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170822_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txs_from', to='core.Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_id_api',
            field=models.CharField(blank=True, default=None, max_length=55, null=True, unique=True),
        ),
    ]
