# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20160601_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
