# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20170914_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressreserve',
            name='need_balance_check',
        ),
    ]
