# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20160604_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_complete',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
