# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20170919_1759'),
        ('core', '0030_remove_addressreserve_need_balance_check'),
    ]

    operations = [
    ]
