# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='test_mode',
            field=models.BooleanField(default=True),
        ),
    ]
