# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 13:31
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_pair_test_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='maximal_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.00'), help_text='Maximal amount that can be set as order base.', max_digits=18),
        ),
    ]
