# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_currency_maximal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('W', 'WITHDRAW'), ('D', 'DEPOSIT')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('W', 'WITHDRAW'), ('D', 'DEPOSIT')], default='D', max_length=1),
        ),
    ]
