# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20160709_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='unique_reference',
        ),
    ]
