# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_currency_maximal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_token',
            field=models.BooleanField(default=False),
        ),
    ]
