# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20171208_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='decimals',
            field=models.IntegerField(default=8),
        ),
    ]
