# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_payment_unique_reference'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paymentmethod',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_slow',
            field=models.BooleanField(default=False),
        ),
    ]
