# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20160710_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpreference',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
        ),
    ]
