# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 12:47
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_currency_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=64, unique=True, validators=[core.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='addressreserve',
            name='address',
            field=models.CharField(max_length=64, unique=True, verbose_name='address_id'),
        ),
    ]
