# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-25 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20171219_1247'),
        ('core', '0036_auto_20171123_1551'),
    ]

    operations = [
    ]
