# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_paymentpreference_currency'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='currency',
            managers=[
            ],
        ),
    ]
