# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20160711_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_preference',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.PaymentPreference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentpreference',
            name='payment_method',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.PaymentMethod'),
        ),
    ]
