# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-28 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20171225_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='fee_offset',
        ),
    ]
