# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-28 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_currency_fee_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='withdrawal_fee',
            field=models.DecimalField(
                decimal_places=8,
                default=0.0,
                max_digits=18),
        ),
    ]
