# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20160718_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_preference',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PaymentPreference'),
        ),
    ]
