# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20160718_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentpreference',
            old_name='identified',
            new_name='identifier',
        ),
    ]
