# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-15 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_currency_withdrawal_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='execute_cover',
            field=models.BooleanField(default=False),
        ),
    ]
