# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20160719_0807'),
        ('core', '0040_auto_20160718_2256'),
    ]

    operations = [
    ]
