# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-16 14:53
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_currency_execute_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='current_slippage',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='currency',
            name='slippage_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.001'), help_text='slippage per coin, 0.001 means 0.1% per coin', max_digits=18),
        ),
        migrations.AddField(
            model_name='currency',
            name='unslippaged_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=18),
        ),
    ]
