# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-16 20:42
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20180116_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='slippage_rate',
            field=models.DecimalField(decimal_places=16, default=Decimal('0.0'), help_text='slippage per coin, 0.001 means 0.1% per coin', max_digits=18),
        ),
    ]
