# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpreference',
            name='currency',
        ),
        migrations.AddField(
            model_name='paymentpreference',
            name='currency',
            field=models.ManyToManyField(null=True, to='core.Currency'),
        ),
    ]
