# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-19 15:12
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180116_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='quote_slippage_rate_multiplier',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.0'), help_text='Multiplies oposite slippage a.k.a in case when this currency is quote.', max_digits=18),
        ),
        migrations.AddField(
            model_name='currency',
            name='quote_unslippaged_amount_multiplier',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.0'), help_text='Multiplies opposite unslippaged amount a.k.a in casewhen this currency is quote.', max_digits=18),
        ),
    ]
