# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20160823_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpreference',
            name='currency',
            field=models.ManyToManyField(to='core.Currency'),
        ),
    ]
