# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-14 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180119_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refunded_transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Transaction'),
        ),
    ]
