# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 11:19
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20160831_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text='Enter phone number in international format. eg. +555198786543',
                max_length=128,
                verbose_name='Phone'),
        ),
    ]
