# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180119_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='ticker',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
