# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20160831_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralTransaction',
            fields=[
                ('transaction_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='core.Transaction')),
            ],
            options={
                'abstract': False,
            },
            bases=(
                'core.transaction',
            ),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disabled',
        ),
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.CharField(
                default=None,
                max_length=39,
                null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(
                default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text='Enter phone number in international format. eg. +555198786543',
                max_length=128,
                verbose_name='Phone'),
        ),
    ]
