# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20160916_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
