# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20160916_1016'),
        ('core', '0046_paymentmethod_is_internal'),
    ]

    operations = [
    ]
