# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20160917_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
