# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-16 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20180228_1149'),
        ('core', '0045_auto_20180313_1433'),
    ]

    operations = [
    ]
