# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-20 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20180301_0856'),
        ('core', '0047_merge_20180316_1223'),
    ]

    operations = [
    ]
