# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-20 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20180316_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='algo',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
