# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-30 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_currency_property_id'),
        ('core', '0048_pair_disable_volume'),
    ]

    operations = [
    ]
