# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-20 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20180320_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('W', 'WITHDRAW'), ('D', 'DEPOSIT'), ('R', 'REFUND'), ('P', 'Referral Payout')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('W', 'WITHDRAW'), ('D', 'DEPOSIT'), ('R', 'REFUND'), ('P', 'Referral Payout')], max_length=1, null=True),
        ),
    ]
