# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-14 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20180320_1112'),
        ('core', '0049_merge_20180430_1245'),
    ]

    operations = [
    ]
