# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge'),
        ('core', '0049_auto_20160919_0249'),
    ]

    operations = [
    ]
