# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-14 08:31
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_merge_20180514_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=127, unique=True, validators=[core.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='currency',
            name='property_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
