# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20160919_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_by_phone',
            field=models.BooleanField(default=True),
        ),
    ]
