# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20180529_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
