# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-02 10:47
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_address_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_tag',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, validators=[core.validators.validate_destination_tag]),
        ),
    ]
