# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-10 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_address_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='last_price_saved',
            field=models.BooleanField(default=False),
        ),
    ]
