# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=18),
        ),
    ]
