# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-11 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_transaction_destination_tag'),
        ('core', '0054_pair_last_price_saved'),
    ]

    operations = [
    ]
