# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20160921_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
