# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-13 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_pair_last_price_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressreserve',
            name='address',
            field=models.CharField(max_length=127, unique=True, verbose_name='address_id'),
        ),
    ]
