# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_merge_20180711_1513'),
        ('core', '0055_auto_20180713_0643'),
    ]

    operations = [
    ]
