# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-22 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_merge_20180711_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('limit', models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=24, null=True)),
                ('type', models.CharField(default='empty', max_length=50)),
                ('description', models.CharField(default='no description', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='currency',
            name='tx_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.TransactionPrice'),
        ),
    ]
