# Generated by Django 2.0.7 on 2018-08-22 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_merge_20180711_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='address',
            name='reserve',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addr', to='core.AddressReserve'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addressreserve',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='addressreserve',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='txs_from', to='core.Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='txs_to', to='core.Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='refunded_transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reserves_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='risk_management.ReservesCover'),
        ),
    ]
