# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_order_is_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
