# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_payment_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_preference',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PaymentPreference'),
        ),
    ]
