# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-18 10:00
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_merge_20180717_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, validators=[core.validators.validate_xmr_payment_id]),
        ),
    ]
