# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_payment_payment_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_seen',
            new_name='last_visit_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_visit_ip',
            field=models.CharField(default=None, max_length=39, null=True),
        ),
    ]
