# Generated by Django 2.0.7 on 2018-08-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_transaction_payment_id'),
        ('core', '0056_auto_20180822_1537'),
    ]

    operations = [
    ]
