# Generated by Django 2.0.7 on 2018-08-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_merge_20180823_0811'),
        ('core', '0056_auto_20180822_0908'),
    ]

    operations = [
    ]
