# Generated by Django 2.0.7 on 2018-08-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_merge_20180823_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='algo',
        ),
        migrations.AddField(
            model_name='currency',
            name='algo_legacy',
            field=models.CharField(blank=True, default=None, help_text='algorithm char field, moved to ForeignKey', max_length=15, null=True),
        ),
    ]
