# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20160922_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
