# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-29 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_transaction_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_completed',
        ),
    ]
