# Generated by Django 2.0.7 on 2018-08-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_merge_20180823_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionprice',
            old_name='type',
            new_name='algo',
        ),
    ]
