# Generated by Django 2.0.7 on 2018-08-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20180829_1100'),
        ('core', '0056_auto_20180822_0908'),
    ]

    operations = [
    ]
