# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_transaction_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='address_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_from', to='core.Address'),
        ),
    ]
