# Generated by Django 2.0.7 on 2018-08-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20180830_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionprice',
            name='algo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CurrencyAlgorithm'),
            preserve_default=False,
        ),
    ]
