# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 13:51
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20161003_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=55, validators=[core.validators.validate_bc]),
        ),
    ]
