# Generated by Django 2.0.7 on 2018-08-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20180830_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionprice',
            name='algo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CurrencyAlgorithm'),
        ),
    ]
