# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 13:58
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20161003_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=35, validators=[core.validators.validate_bc]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_id',
            field=models.CharField(default=None, max_length=55, null=True),
        ),
    ]
