# Generated by Django 2.0.7 on 2018-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20180830_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionprice',
            name='type',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]