# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20161003_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seofooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('head', models.TextField(default=None, null=True)),
                ('body', models.TextField(default=None, null=True)),
                ('locale', models.TextField(default=None, null=True)),
            ],
        ),
    ]
