# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_seofooter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seofooter',
            name='locale',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
    ]
