# Generated by Django 2.0.7 on 2018-08-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_transactionprice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionprice',
            name='type',
        ),
    ]
