# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20161004_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='seofooter',
            name='written_by',
            field=models.TextField(default=None, null=True),
        ),
    ]
