# Generated by Django 2.0.7 on 2018-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_transactionprice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='min_order_book_confirmations',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
