# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_seofooter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seofooter',
            name='type',
            field=models.CharField(choices=[('About Us', 'About Us'), ('Careers', 'Careers'), ('Press', 'Press'), ('Conference', 'Conference'), ('Legal & Privacy', 'Legal & Privacy'), ('Security', 'Security'), ('FAQ', 'FAQ'), ('Blog', 'Blog'), ('Fees', 'Fees'), ('Support', 'Support'), ('Trading Guide', 'Trading Guide')], default=None, max_length=50),
        ),
    ]
