# Generated by Django 2.0.7 on 2018-11-26 16:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_transaction_limit_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('discount_part', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
