# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20161004_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seofooter',
            new_name='CmsPage',
        ),
    ]
