# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20161005_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspage', name='locale', field=models.CharField(
                choices=[
                    ('ru', 'Russian'), ('en', 'English'), ('es', 'Espanol')], default=(
                    'ru', 'Russian'), max_length=2, null=True), ), ]
