# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20161009_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('currency_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='core.Currency')),
                ('min_confirmation',
                 models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(
                'core.currency',
            ),
            managers=[
                ('active_objects',
                 django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='name',
            field=models.CharField(
                choices=[
                    ('faq',
                     'faq'),
                    ('blog',
                     'blog'),
                    ('fees',
                     'fees'),
                    ('support',
                     'support'),
                    ('trading_guide',
                     'trading_guide'),
                    ('about_us',
                     'about_us'),
                    ('careers',
                     'careers'),
                    ('press',
                     'press'),
                    ('conference',
                     'conference'),
                    ('legal_privacy',
                     'legal_privacy'),
                    ('security',
                     'security')],
                default=None,
                max_length=50),
        ),
    ]
