# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20161009_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='min_confirmation',
            new_name='min_confirmations',
        ),
    ]
