# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20161009_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='min_confirmations',
        ),
        migrations.AddField(
            model_name='currency',
            name='min_confirmations',
            field=models.IntegerField(
                default=None),
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='name',
            field=models.CharField(
                choices=[
                    ('faq',
                     'faq'),
                    ('blog',
                     'blog'),
                    ('fees',
                     'fees'),
                    ('support',
                     'support'),
                    ('trading_guide',
                     'trading_guide'),
                    ('about_us',
                     'about_us'),
                    ('careers',
                     'careers'),
                    ('press',
                     'press'),
                    ('conference',
                     'conference'),
                    ('legal_privacy',
                     'legal_privacy'),
                    ('security',
                     'security')],
                default=None,
                max_length=50),
        ),
    ]
