# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0009_remove_referral_ip'),
        ('core', '0094_auto_20161019_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='currency_ptr',
        ),
        migrations.DeleteModel(
            name='CryptoCurrency',
        ),
    ]
