# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 04:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0098_auto_20161031_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='BraintreePaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ident', models.CharField(blank=True, max_length=60, null=True, verbose_name='Identification')),
                ('uni', models.CharField(blank=True, max_length=60, null=True, verbose_name='Uni')),
                ('nonce', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nonce')),
                ('token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Token')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentmethods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='sig_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='name',
            field=models.CharField(choices=[('about_us', 'about_us'), ('careers', 'careers'), ('press', 'press'), ('conference', 'conference'), ('legal_privacy', 'legal_privacy'), ('security', 'security'), ('faq', 'faq'), ('blog', 'blog'), ('fees', 'fees'), ('support', 'support'), ('trading_guide', 'trading_guide')], default=None, max_length=50),
        ),
    ]
