# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_auto_20161102_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='BraintreePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Token')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Payment')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.BraintreePaymentMethod')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='name',
            field=models.CharField(choices=[('faq', 'faq'), ('blog', 'blog'), ('fees', 'fees'), ('support', 'support'), ('trading_guide', 'trading_guide'), ('about_us', 'about_us'), ('careers', 'careers'), ('press', 'press'), ('conference', 'conference'), ('legal_privacy', 'legal_privacy'), ('security', 'security')], default=None, max_length=50),
        ),
    ]
