# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_auto_20161102_1508'),
        ('core', '0096_auto_20161030_0252'),
        ('core', '0095_auto_20161026_2018'),
    ]

    operations = [
    ]
