# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-09 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20161108_2208'),
        ('core', '0097_auto_20161108_1025'),
    ]

    operations = [
    ]
