# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='ip',
            field=models.CharField(default=None, max_length=39, null=True),
        ),
    ]
