# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_auto_20161216_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='percent_first_degree',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='program',
            name='percent_second_degree',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='program',
            name='percent_third_degree',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
