# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referral_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='link',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
