# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_auto_20160831_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
