# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_auto_20170307_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='test_scenario',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
