# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_auto_20160912_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
