# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_auto_20160912_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referrer',
        ),
        migrations.AddField(
            model_name='program',
            name='max_users',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='referral',
            name='code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='referrals.ReferralCode'),
        ),
        migrations.AddField(
            model_name='referral',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='ip',
            field=models.CharField(default=None, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='max_payout_btc',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='program',
            name='percent_second_degree',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='percent_third_degree',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee', to=settings.AUTH_USER_MODEL),
        ),
    ]
