# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_auto_20170331_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.ForeignKey(default=None, help_text='Use this link to refer users and earn free Bitcoins', null=True, on_delete=django.db.models.deletion.CASCADE, to='referrals.ReferralCode'),
        ),
    ]
