# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_auto_20160916_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='max_lifespan',
            field=models.IntegerField(default=-1),
        ),
    ]
