# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_auto_20170920_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_set', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=set([]),
        ),
    ]
