# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_auto_20160921_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
    ]
