# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_auto_20160921_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='ip',
        ),
    ]
