# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_released', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasepayment',
            name='payment',
            field=models.CharField(max_length=10),
        ),
    ]
