# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_released', '0002_auto_20160927_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasepayment',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
