# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_released', '0004_auto_20160927_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasepayment',
            name='payment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='core.Payment'),
        ),
    ]
