# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_released', '0005_auto_20160927_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasepayment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='releasepayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReleasePayment',
        ),
    ]
