# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-03 11:48
from __future__ import unicode_literals

import core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0026_merge_20180315_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sending_address', models.CharField(blank=True, max_length=42, null=True, validators=[core.validators.validate_eth])),
                ('user_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('contribution', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('orders', models.ManyToManyField(blank=True, null=True, to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
