# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-03 14:37
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0002_auto_20180503_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UtmSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='address_turnover',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Converted to ETH', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='eth_balance',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='potential',
            field=models.IntegerField(choices=[(0, 'UNDEFINED'), (-5, 'LOW'), (5, 'MEDIUM'), (10, 'HIGH')], default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='ico.Category'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='utm_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ico.UtmSource'),
        ),
    ]
