# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-04 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0003_auto_20180703_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.ManyToManyField(blank=True, to='ico.Category'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='orders',
            field=models.ManyToManyField(blank=True, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
