# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-04 15:12
from __future__ import unicode_literals

import core.validators
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_address_blocked'),
        ('ico', '0004_auto_20180704_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True)),
                ('balance_eth', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('address', models.CharField(blank=True, max_length=42, null=True, validators=[core.validators.validate_eth])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='tokens_balance_eth',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ico.Subscription'),
        ),
    ]
