# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-05 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_auto_20180223_1407'),
        ('ico', '0006_subscription_related_turnover'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referrals.ReferralCode'),
        ),
        migrations.AddField(
            model_name='utmsource',
            name='referral_codes',
            field=models.ManyToManyField(blank=True, to='referrals.ReferralCode'),
        ),
    ]
