# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-19 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0007_auto_20180705_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='ico_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
