# Generated by Django 2.0.7 on 2018-08-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0008_auto_20180719_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='referrals.ReferralCode'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='utm_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ico.UtmSource'),
        ),
    ]
