# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-20 01:31
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20170220_0130'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number in international format. eg. +44020786543', max_length=128, verbose_name='Phone')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_company', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('last_visit_ip', models.CharField(default=None, max_length=39, null=True)),
                ('last_visit_time', models.DateTimeField(default=None, null=True)),
                ('notify_by_phone', models.BooleanField(default=True)),
                ('notify_by_email', models.BooleanField(default=True)),
                ('ip', models.CharField(default=None, max_length=39, null=True)),
                ('lang', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Espanol')], default='en', max_length=100)),
                ('sig_key', models.CharField(blank=True, max_length=64)),
                ('duplicate_of', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmsToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('sms_token', models.CharField(blank=True, max_length=4)),
                ('send_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserDuplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('duplication_reason', models.IntegerField(choices=[(1, 'Duplicate Wallet'), (2, 'Duplicate IP'), (3, 'Duplicate User Agent'), (4, 'Duplicate Email')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NexchangeUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userduplication',
            name='duplicate_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userduplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
