# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170301_0922'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='smstoken',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='time_zone',
            field=models.CharField(default=None, max_length=100,
                                   null=True, blank=True),
        ),
    ]
