# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170117_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(
                choices=[
                    ('ru',
                     'Russian'),
                    ('en',
                     'English'),
                    ('es',
                     'Espanol')],
                max_length=100,
                null=True),
        ),
    ]
