# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170331_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.CharField(choices=[('ru-ru', 'Russian'), ('en-en', 'English'), ('es-es', 'Spanish'), ('es-ca', 'Catalan')], default='en', max_length=100),
        ),
    ]
