# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170411_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Spanish'), ('ca', 'Catalan')], default='en', max_length=100),
        ),
    ]
