# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.CharField(
                choices=[
                    ('ru',
                     'Russian'),
                    ('en',
                     'English'),
                    ('es',
                     'Espanol')],
                default='en',
                max_length=100),
        ),
    ]
