# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170415_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.CharField(
                choices=[
                    ('ru',
                     'Russian'),
                    ('en',
                     'English'),
                    ('es',
                     'Spanish'),
                    ('ca',
                     'Catalan'),
                    ('zh-hans',
                     'Simplified Chinese')],
                default='en',
                max_length=100),
        ),
    ]
