# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_affiliate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliate_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
    ]
