# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_profile_duplicate_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDuplication',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_on',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('modified_on',
                 models.DateTimeField(
                     auto_now=True)),
                ('duplication_reason',
                 models.IntegerField(
                     choices=[
                         (1,
                          'Duplicate Wallet'),
                         (2,
                          'Duplicate IP'),
                         (3,
                          'Duplicate User Agent'),
                         (4,
                          'Duplicate Email')],
                     max_length=2)),
                ('duplicate_of',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='original_user_set',
                     to=settings.AUTH_USER_MODEL)),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='duplicate_set',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
