# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 09:28
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170419_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number in international format. eg. +44020786543', max_length=128, null=True, unique=True, verbose_name='Phone'),
        ),
    ]
