# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170423_1229'),
        ('accounts', '0007_auto_20170419_0855'),
    ]

    operations = [
    ]
