# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userduplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userduplication',
            name='duplication_reason',
            field=models.IntegerField(
                choices=[
                    (1,
                     'Duplicate Wallet'),
                    (2,
                     'Duplicate IP'),
                    (3,
                     'Duplicate User Agent'),
                    (4,
                     'Duplicate Email')]),
        ),
    ]
