# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20170505_0224'),
        ('accounts', '0008_auto_20170430_0928'),
    ]

    operations = [
    ]
