# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170213_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstoken',
            name='send_count',
            field=models.IntegerField(default=0),
        ),
    ]
