# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20170507_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anonymous_login',
            field=models.BooleanField(default=False),
        ),
    ]
