# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_anonymous_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cards_validity_approved',
            field=models.BooleanField(default=False),
        ),
    ]
