# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_cards_validity_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ip',
            field=models.CharField(blank=True, default=None, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_visit_ip',
            field=models.CharField(blank=True, default=None, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_visit_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
