# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_use_test_mode',
            field=models.BooleanField(default=False),
        ),
    ]
