# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_do_auto_referral_payouts'),
        ('accounts', '0013_profile_tier'),
    ]

    operations = [
    ]
