# Generated by Django 2.0.7 on 2018-08-22 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_can_use_test_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliate_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='verification.VerificationTier'),
        ),
        migrations.AlterField(
            model_name='userduplication',
            name='duplicate_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='original_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userduplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='duplicate_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
