# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={
                'ordering': ['-created_on'],
                'verbose_name': 'Support',
                'verbose_name_plural': 'Support'},
        ),
        migrations.RemoveField(
            model_name='support',
            name='created',
        ),
        migrations.AddField(
            model_name='support',
            name='created_on',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='support',
            name='modified_on',
            field=models.DateTimeField(
                auto_now=True),
        ),
        migrations.AddField(
            model_name='support',
            name='unique_reference',
            field=models.CharField(
                default='placeholder',
                max_length=16),
            preserve_default=False,
        ),
    ]
