# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0006_auto_20170206_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_prices', to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='price',
            name='ticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticker.Ticker'),
        ),
    ]
