# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:40
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_currency_fee_offset'),
        ('ticker', '0007_auto_20170206_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=18)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='core.Currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_prices', to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='price',
            name='base',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='base',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='quote',
        ),
        migrations.AddField(
            model_name='price',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticker.Pair'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticker.Pair'),
            preserve_default=False,
        ),
    ]
