# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0009_auto_20170207_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='pair',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
