# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0010_pair_pair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='pair',
            new_name='name',
        ),
    ]
