# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0011_auto_20170207_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
