# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:10
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0013_auto_20170208_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='fee',
        ),
        migrations.AddField(
            model_name='pair',
            name='fee_ask',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.02'), max_digits=18),
        ),
        migrations.AddField(
            model_name='pair',
            name='fee_bid',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.02'), max_digits=18),
        ),
    ]
