# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170209_1218'),
        ('ticker', '0014_auto_20170208_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='base',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='quote',
        ),
        migrations.AlterField(
            model_name='price',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pair'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pair'),
        ),
        migrations.DeleteModel(
            name='Pair',
        ),
    ]
