# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-24 16:19
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0044_auto_20180119_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('tx_id', models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('address_from', models.CharField(blank=True, max_length=64, null=True)),
                ('address_to', models.CharField(blank=True, max_length=64, null=True)),
                ('auto_comment', models.TextField(blank=True, default=None, null=True)),
                ('human_comment', models.TextField(blank=True, default=None, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
