# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspicioustransactions',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
