# Generated by Django 2.0.7 on 2019-02-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20180822_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousTransactionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Suspicious transaction category',
                'verbose_name_plural': 'Suspicious transaction categories',
            },
        ),
        migrations.AlterModelOptions(
            name='suspicioustransactions',
            options={'verbose_name': 'Suspicious transaction', 'verbose_name_plural': 'Suspicious transactions'},
        ),
        migrations.AddField(
            model_name='suspicioustransactions',
            name='categories',
            field=models.ManyToManyField(blank=True, to='audit.SuspiciousTransactionCategory'),
        ),
    ]
