# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='price',
            name='modified_on',
        ),
    ]
