# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='better_adds_count',
            field=models.IntegerField(default=0),
        ),
    ]
