# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_aud',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='rate_aud',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12),
            preserve_default=False,
        ),
    ]
