# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
