# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_market'),
        ('ticker', '0002_auto_20170607_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Market'),
        ),
    ]
