# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 09:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_price_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='slippage',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
    ]
