# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_price__price_eur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='rate',
            new_name='price_eur',
        ),
        migrations.RemoveField(
            model_name='price',
            name='_price_eur',
        ),
        migrations.AddField(
            model_name='price',
            name='rate_eur',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='rate_usd',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
