# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_currency_fee_offset'),
        ('ticker', '0003_auto_20170203_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ask', models.DecimalField(decimal_places=8, max_digits=18)),
                ('bid', models.DecimalField(decimal_places=8, max_digits=18)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_ticker', to='core.Currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_ticker', to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
