# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_auto_20160720_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='rate_eur',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='rate_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
