# Generated by Django 2.0.7 on 2018-08-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_price_slippage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Market'),
        ),
    ]
