# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='ticker_eth',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prices_eth',
                to='ticker.Ticker'),
        ),
        migrations.AddField(
            model_name='price',
            name='ticker_ltc',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prices_ltc',
                to='ticker.Ticker'),
        ),
    ]
