# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0005_auto_20160919_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='price',
            name='rate_eur',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='price',
            name='rate_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
