# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:41
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pair'),
        ('ticker', '0006_auto_20170209_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('fee_ask', models.DecimalField(decimal_places=8, default=Decimal('0.02'), max_digits=18)),
                ('fee_bid', models.DecimalField(decimal_places=8, default=Decimal('0.02'), max_digits=18)),
                ('name', models.CharField(blank=True, max_length=8, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_base_prices', to='core.Currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_quote_prices', to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='price',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticker.Pair'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Pair'),
        ),
    ]
