# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_address_order'),
        ('orders', '0002_auto_20161215_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='withdraw_address',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order_set',
                to='core.Address'),
        ),
    ]
