# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170220_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_reference',
            field=models.CharField(max_length=16),
        ),
    ]
