# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_withdraw_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_default_rule',
            field=models.BooleanField(default=False),
        ),
    ]
