# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_default_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='moderator_flag',
            field=models.IntegerField(default=None),
        ),
    ]
