# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_moderator_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_cash',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
