# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0008_auto_20170210_0759'),
        ('core', '0012_auto_20170213_1727'),
        ('orders', '0006_auto_20170209_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_btc',
            new_name='amount_base',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_completed',
            new_name='from_default_rule',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount_cash',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_failed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_released',
        ),
        migrations.RemoveField(
            model_name='order',
            name='moderator_flag',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_quote',
            field=models.DecimalField(
                decimal_places=8,
                default=1,
                max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pair',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.Pair'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='ticker.Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(
                choices=[
                    (0,
                     'CANCELED'),
                    (1,
                     'INITIAL'),
                    (2,
                     'PAID'),
                    (3,
                     'RELEASED'),
                    (4,
                     'COMPLETED')],
                default=1,
                help_text='INITIAL - Initial state of the order.<br/>PAID - Order is Paid by customer. Could be paid by crypto transaction or fiat payment, depending on order_type.<br/>RELEASED - Order is paid by service provider. Could be paid by crypto transaction or fiat payment, depending on order_type.<br/>COMPLETED - All states of the order is completed<br/>CANCELED - Order is canceled..'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(
                choices=[
                    (0,
                     'SELL'),
                    (1,
                     'BUY'),
                    (2,
                     'EXCHANGE')],
                default=1,
                help_text='BUY - Customer is giving fiat, and getting crypto money.<br/>SELL - Customer is giving crypto and getting fiat money<br/>EXCHANGE - Customer is exchanging different kinds of crypto currencies.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unique_reference',
            field=models.CharField(
                max_length=5),
        ),
    ]
