# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20170213_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_marked_as_paid',
            field=models.BooleanField(default=False),
        ),
    ]
