# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-11 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20170210_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_default_rule',
            field=models.BooleanField(default=False),
        ),
    ]
