# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170301_0922'),
        ('orders', '0007_auto_20170322_0713'),
    ]

    operations = [
    ]
