# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_user_marked_as_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='system_marked_as_paid',
            field=models.BooleanField(default=False),
        ),
    ]
