# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20170615_1304'),
        ('orders', '0010_order_flagged'),
    ]

    operations = [
    ]
