# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20170804_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='withdraw_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_set_withdraw', to='core.Address'),
        ),
    ]
