# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170731_1413'),
        ('orders', '0013_auto_20170814_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_set_deposit', to='core.Address'),
        ),
    ]
