# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_deposit_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_window',
            field=models.IntegerField(default=15),
        ),
    ]
