# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20170816_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_reference',
            field=models.CharField(max_length=16),
        ),
    ]
