# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20170908_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_base',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_quote',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18),
        ),
    ]
