# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20170921_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_provided_amount',
            field=models.IntegerField(choices=[(0, 'amount_base'), (1, 'amount_quote'), (2, 'amount_quote and amount_base')], default=0),
        ),
    ]
