# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-25 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_slippage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unpaid_order_window',
            field=models.IntegerField(default=45),
        ),
    ]
