# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-15 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20180216_0836'),
        ('orders', '0024_order_unpaid_order_window'),
    ]

    operations = [
    ]
