# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 15:18
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_merge_20180315_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, validators=[core.validators.validate_xmr_payment_id]),
        ),
    ]
