# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='set_as_paid_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
