# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-02 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_destination_tag'),
        ('orders', '0028_order_set_as_paid_on'),
    ]

    operations = [
    ]
