# Generated by Django 2.0.7 on 2018-08-22 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_merge_20180702_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deposit_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_set_deposit', to='core.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pair'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_preference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.PaymentPreference'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticker.Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_set_refund', to='core.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='withdraw_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_set_withdraw', to='core.Address'),
        ),
    ]
