# Generated by Django 2.0.7 on 2018-10-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20180822_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_identity_token',
            field=models.BooleanField(default=True, help_text='If True - user can use auto id checking service(Idenfy).'),
        ),
    ]
