# Generated by Django 2.0.7 on 2018-10-26 15:46

import audit_log.models.fields
import core.common.models
import core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_fsm
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_currency_min_order_book_confirmations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0031_order_return_identity_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('flagged', models.BooleanField(default=False)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('order_type', models.IntegerField(choices=[(0, 'SELL'), (1, 'BUY')], default=1, help_text='BUY - Buy base currency (1).<br/>SELL - Sell base currency (0).<br/>')),
                ('payment_id', models.CharField(blank=True, default=None, max_length=64, null=True, validators=[core.validators.validate_xmr_payment_id])),
                ('destination_tag', models.CharField(blank=True, default=None, max_length=10, null=True, validators=[core.validators.validate_destination_tag])),
                ('exchange', models.BooleanField(default=False)),
                ('amount_base', models.DecimalField(blank=True, decimal_places=8, max_digits=18)),
                ('amount_quote', models.DecimalField(blank=True, decimal_places=8, max_digits=18)),
                ('unique_reference', models.CharField(max_length=16)),
                ('admin_comment', models.CharField(max_length=200)),
                ('rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('limit_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('closed_amount_base', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True)),
                ('closed_amount_quote', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=18, null=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(12, 'UNCONFIRMED PAYMENT'), (14, 'PRE-RELEASE'), (0, 'CANCELED'), (11, 'INITIAL'), (13, 'PAID'), (15, 'RELEASED'), (16, 'COMPLETED'), (8, 'REFUNDED')], db_index=True, default=11, help_text='INITIAL - Initial status of the order.<br/>PAID - Order is Paid by customer. Could be paid by crypto transaction or fiat payment, depending on order_type.<br/>PAID_UNCONFIRMED - Order is possibly paid (unconfirmed crypto transaction or fiat payment is to small to cover the order.)<br/>PRE_RELEASE - Order is prepared for RELEASE.<br/>RELEASED - Order is paid by service provider. Could be paid by crypto transaction or fiat payment, depending on order_type.<br/>COMPLETED - All statuses of the order is completed<br/>CANCELED - Order is canceled.<br/>REFUNDED - Order is refunded<br/>')),
                ('book_status', django_fsm.FSMIntegerField(choices=[(0, 'NEW'), (5, 'OPEN'), (10, 'CLOSED')], db_index=True, default=0, help_text='NEW - Order is created, not on the book.<br/>OPEN - Order is on the book.<br/>CLOSED - Order is closed, not on the book anymore.<br/>')),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders_limitorder_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deposit_address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='limitorder_set_deposit', to='core.Address')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_orders_limitorder_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.common.models.UniqueFieldMixin, models.Model),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('flagged', models.BooleanField(default=False)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('book_obj', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders_orderbook_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_orders_orderbook_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('pair', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pair')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.common.models.UniqueFieldMixin, models.Model),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('flagged', models.BooleanField(default=False)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('amount_base', models.DecimalField(blank=True, decimal_places=8, max_digits=18)),
                ('amount_quote', models.DecimalField(blank=True, decimal_places=8, max_digits=18)),
                ('unique_reference', models.CharField(max_length=16)),
                ('admin_comment', models.CharField(max_length=200)),
                ('rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('buy_order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_trades', to='orders.LimitOrder')),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders_trade_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_orders_trade_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('order_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.OrderBook')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pair')),
                ('sell_order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sell_trades', to='orders.LimitOrder')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.common.models.UniqueFieldMixin, models.Model),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders_order_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_with_session_key',
            field=audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_orders_order_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_with_session_key',
            field=audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[(0, 'SELL'), (1, 'BUY')], default=1, help_text='BUY - Buy base currency (1).<br/>SELL - Sell base currency (0).<br/>'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(12, 'UNCONFIRMED PAYMENT'), (14, 'PRE-RELEASE'), (0, 'CANCELED'), (11, 'INITIAL'), (13, 'PAID'), (15, 'RELEASED'), (16, 'COMPLETED'), (8, 'REFUNDED')], default=11, help_text='INITIAL - Initial status of the order.<br/>PAID - Order is Paid by customer. Could be paid by crypto transaction or fiat payment, depending on order_type.<br/>PAID_UNCONFIRMED - Order is possibly paid (unconfirmed crypto transaction or fiat payment is to small to cover the order.)<br/>PRE_RELEASE - Order is prepared for RELEASE.<br/>RELEASED - Order is paid by service provider. Could be paid by crypto transaction or fiat payment, depending on order_type.<br/>COMPLETED - All statuses of the order is completed<br/>CANCELED - Order is canceled.<br/>REFUNDED - Order is refunded<br/>'),
        ),
        migrations.AddField(
            model_name='limitorder',
            name='order_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.OrderBook'),
        ),
        migrations.AddField(
            model_name='limitorder',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pair'),
        ),
        migrations.AddField(
            model_name='limitorder',
            name='refund_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='limitorder_set_refund', to='core.Address'),
        ),
        migrations.AddField(
            model_name='limitorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='limitorders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limitorder',
            name='withdraw_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='limitorder_set_withdraw', to='core.Address'),
        ),
    ]
