# Generated by Django 2.0.7 on 2018-12-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0010_auto_20180926_1434'),
        ('orders', '0033_feesource_orderfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referred_with',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='referrals.ReferralCode'),
        ),
    ]
