# Generated by Django 2.0.7 on 2018-12-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_order_referred_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='set_as_paid_unconfirmed_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='set_as_released_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
